# Generated by Django 2.0.2 on 2018-02-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Email_Address',
        ),
    ]
