# Generated by Django 2.0.2 on 2018-02-24 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180224_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=80, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='email_address',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Cafe'),
            preserve_default=False,
        ),
    ]
